################################
#                              #
#   bundle exec jekyll serve   #
#                              # 
################################

# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://sibosendteam.github.io
date_format: "ordinal"
title: Sibosend Team
subtitle: "聪明在于勤奋，天才在于积累"
# description: "#####"
keywords: sibosend,sibosend team,team
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Chen minghua
organization: 

organization_url: 
github_username: sibosendteam
location: Beijing, China
email: support@sibosend.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: sibosendteam
# repository: sibosend

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
# comments_provider: gitalk
# !!!important!!! your application for
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
# disqus:
#     username: 
# https://imsun.net/posts/gitment-introduction/
# gitment:
#     owner: mzlogin
#     repo: blog-comments
#     oauth:
#         client_id: d2e1cbbd298958076462
        # client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
# gitalk:
#     owner: mzlogin
#     repo: blog-comments
#     clientID: d2e1cbbd298958076462
    # clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # Is full-text search
    fulltext: true
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
# google:
#     analytics_id: UA-80669434-1
